name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install minimal test dependencies
        # We intentionally install only minimal packages used by unit tests to avoid heavy native builds (pyarrow, etc.)
        run: |
          python -m pip install pandas pytest

      - name: Run unit tests (repo tests folder)
        working-directory: product-aggregator
        run: python -m pytest -q tests

  # NOTE: Integration tests that require a browser/driver (Selenium/undetected-chromedriver)
  # should be added as a separate job or workflow, and run only on self-hosted runners
  # or when explicitly requested, to avoid flaky/cloud runner/browser compatibility issues.
